version: 2

jobs:
  create-binary:
    working_directory: ~/go/src/s5s
    docker:
      - image: cimg/go:1.13
    parameters:
      os:
        description: Operating System
        type: string
      arch:
        description: Architecture
        type: string
      filename:
        description: Output Filename
        type: string
        default: s5s
    environment:
      - GOOS: << parameters.os >>
      - GOARCH: << parameters.arch >>
      - BUILD_FILENAME: << parameters.filename >>
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: go get
      - run:
          name: Build Binary
          command: go build -o /tmp/artifacts/$GOOS/$BUILD_FILENAME .
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts
  publish-release:
    docker:
      - image: cimg/go:1.13
    parameters:
      os:
        description: Operating System
        type: string
      filename:
        description: Output Filename
        type: string
        default: s5s
    environment:
      - BUILD_DISTRO: << parameters.os >>
      - BUILD_FILENAME: << parameters.filename >>
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Install GHR
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Publish to GitHub
          command: |
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete $BUILD_DISTRO-$CIRCLE_SHA1 /tmp/artifacts/$BUILD_DISTRO/$BUILD_FILENAME
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete $BUILD_DISTRO-latest /tmp/artifacts/$BUILD_DISTRO/$BUILD_FILENAME

workflows:
  version: 2
  publish-windows-binary:
    jobs:
      - create-binary:
          os: windows
          arch: amd64
          filename: s5s.exe
      - publish-release:
          os: windows
          filename: s5s.exe
          requires:
            - create-binary
          filters:
            branches:
              only:
                - master
  publish-linux-binary:
    jobs:
      - create-binary:
          os: linux
          arch: amd64
          filename: s5s
      - publish-release:
          os: linux
          filename: s5s
          requires:
            - create-binary
          filters:
            branches:
              only:
                - master
  publish-darwin-binary:
    jobs:
      - create-binary:
          os: darwin
          arch: amd64
          filename: s5s
      - publish-release:
          os: darwin
          filename: s5s
          requires:
            - create-binary
          filters:
            branches:
              only:
                - master
