version: 2

jobs:
  create-binary: &create-binary
    working_directory: ~/go/src/s5s
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: go get
      - run:
          name: Build Binary
          command: go build -o /tmp/artifacts/$GOOS/s5s .
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts
  create-windows-binary:
    <<: *create-binary
    environment:
      - GOOS: windows
      - GOARCH: amd64
  create-linux-binary:
    <<: *create-binary
    environment:
      - GOOS: linux
      - GOARCH: amd64
  create-macos-binary:
    <<: *create-binary
    environment:
      - GOOS: darwin
      - GOARCH: amd64
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete windows-$CIRCLE_SHA1 /tmp/artifacts/windows/s5s
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete windows-latest /tmp/artifacts/windows/s5s
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete linux-$CIRCLE_SHA1 /tmp/artifacts/linux/s5s
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete linux-latest /tmp/artifacts/linux/s5s
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete darwin-$CIRCLE_SHA1 /tmp/artifacts/darwin/s5s
            ghr -t $GITHUB_TOKEN -U $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPORNAME -c $CIRCLE_SHA1 -delete darwin-latest /tmp/artifacts/darwin/s5s

workflows:
  version: 2
  build-and-publish:
    jobs:
      - create-windows-binary
      - create-linux-binary
      - create-macos-binary
      - publish-github-release:
          context: github-publishing
          requires:
            - create-windows-binary
            - create-linux-binary
            - create-macos-binary
          filters:
            branches:
              only:
                - master
